// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc_models

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID                 int32
	UserID             pgtype.Int4
	Filename           pgtype.Text
	Location           pgtype.Text
	CommentID          pgtype.Int4
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	Filesize           pgtype.Int4
	FileFileName       pgtype.Text
	FileContentType    pgtype.Text
	FileFileSize       pgtype.Int4
	FileUpdatedAt      pgtype.Timestamp
	AttachableID       pgtype.Int4
	AttachableType     pgtype.Text
	MigratedToDocument bool
}

type BlacklistedPassword struct {
	ID        int32
	String    pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type BlockedDomain struct {
	ID   int64
	Name pgtype.Text
}

type Chatbot struct {
	ID               int64
	Kind             pgtype.Text
	Server           pgtype.Text
	Channel          pgtype.Text
	AccessToken      pgtype.Text
	AuthorID         pgtype.Int4
	GroupID          pgtype.Int4
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	Name             pgtype.Text
	NotificationOnly bool
	WebhookKind      pgtype.Text
	EventKinds       []string
}

type Cohort struct {
	ID      int32
	StartOn pgtype.Date
	EndOn   pgtype.Date
}

type Comment struct {
	ID                int32
	DiscussionID      pgtype.Int4
	Body              pgtype.Text
	UserID            pgtype.Int4
	ParentID          pgtype.Int4
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	UsesMarkdown      bool
	CommentVotesCount int32
	AttachmentsCount  int32
	EditedAt          pgtype.Timestamp
	VersionsCount     pgtype.Int4
	BodyFormat        string
	Attachments       []byte
	DiscardedAt       pgtype.Timestamp
	DiscardedBy       pgtype.Int4
	SecretToken       pgtype.Text
	ContentLocale     pgtype.Text
	LinkPreviews      []byte
	ParentType        string
}

type DefaultGroupCover struct {
	ID                    int32
	CoverPhotoFileName    pgtype.Text
	CoverPhotoContentType pgtype.Text
	CoverPhotoFileSize    pgtype.Int4
	CoverPhotoUpdatedAt   pgtype.Timestamp
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

type Demo struct {
	ID          int64
	AuthorID    int32
	GroupID     int32
	Name        string
	Description pgtype.Text
	RecordedAt  pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Priority    int32
	DemoHandle  pgtype.Text
}

type Discussion struct {
	ID                  int32
	GroupID             pgtype.Int4
	AuthorID            pgtype.Int4
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	Title               pgtype.Text
	LastCommentAt       pgtype.Timestamp
	Description         pgtype.Text
	UsesMarkdown        bool
	ItemsCount          int32
	ClosedAt            pgtype.Timestamp
	Private             bool
	Key                 pgtype.Text
	IframeSrc           pgtype.Text
	LastActivityAt      pgtype.Timestamp
	LastSequenceID      int32
	FirstSequenceID     int32
	VersionsCount       pgtype.Int4
	ClosedPollsCount    int32
	Pinned              bool
	Importance          int32
	SeenByCount         int32
	RangesString        pgtype.Text
	GuestGroupID        pgtype.Int4
	DescriptionFormat   string
	Attachments         []byte
	Info                []byte
	MaxDepth            int32
	NewestFirst         bool
	DiscardedAt         pgtype.Timestamp
	SecretToken         pgtype.Text
	MembersCount        pgtype.Int4
	AnonymousPollsCount int32
	ContentLocale       pgtype.Text
	LinkPreviews        []byte
	PinnedAt            pgtype.Timestamp
	DiscardedBy         pgtype.Int4
	Template            bool
	SourceTemplateID    pgtype.Int4
}

type DiscussionReader struct {
	ID                 int32
	UserID             int32
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	DiscussionID       int32
	LastReadAt         pgtype.Timestamp
	LastReadSequenceID int32
	Volume             int32
	Participating      bool
	DismissedAt        pgtype.Timestamp
	ReadRangesString   pgtype.Text
	InviterID          pgtype.Int4
	Token              pgtype.Text
	RevokedAt          pgtype.Timestamp
	Admin              bool
	AcceptedAt         pgtype.Timestamp
	RevokerID          pgtype.Int4
}

type DiscussionSearchVector struct {
	ID           int32
	DiscussionID pgtype.Int4
	SearchVector interface{}
}

type Document struct {
	ID              int32
	ModelID         pgtype.Int4
	ModelType       pgtype.Text
	Title           pgtype.Text
	Url             pgtype.Text
	Doctype         string
	Color           string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Icon            pgtype.Text
	AuthorID        int32
	WebUrl          pgtype.Text
	ThumbUrl        pgtype.Text
	FileFileName    pgtype.Text
	FileContentType pgtype.Text
	GroupID         pgtype.Int4
}

type Event struct {
	ID                 int32
	Kind               pgtype.Text
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	EventableID        pgtype.Int4
	EventableType      pgtype.Text
	UserID             pgtype.Int4
	DiscussionID       pgtype.Int4
	SequenceID         pgtype.Int4
	Announcement       bool
	CustomFields       []byte
	ParentID           pgtype.Int4
	Position           int32
	ChildCount         int32
	Depth              int32
	Pinned             bool
	PositionKey        pgtype.Text
	DescendantCount    int32
	EventableVersionID pgtype.Int4
}

type Group struct {
	ID                             int32
	Name                           pgtype.Text
	CreatedAt                      pgtype.Timestamp
	UpdatedAt                      pgtype.Timestamp
	ParentID                       pgtype.Int4
	Description                    pgtype.Text
	MembershipsCount               int32
	ArchivedAt                     pgtype.Timestamp
	DiscussionsCount               int32
	FullName                       pgtype.Text
	ParentMembersCanSeeDiscussions bool
	Key                            pgtype.Text
	CategoryID                     pgtype.Int4
	Handle                         interface{}
	ThemeID                        pgtype.Int4
	IsVisibleToPublic              bool
	IsVisibleToParentMembers       bool
	DiscussionPrivacyOptions       string
	MembersCanAddMembers           bool
	MembershipGrantedUpon          string
	MembersCanEditDiscussions      bool
	CoverPhotoFileName             pgtype.Text
	CoverPhotoContentType          pgtype.Text
	CoverPhotoFileSize             pgtype.Int4
	CoverPhotoUpdatedAt            pgtype.Timestamp
	LogoFileName                   pgtype.Text
	LogoContentType                pgtype.Text
	LogoFileSize                   pgtype.Int4
	LogoUpdatedAt                  pgtype.Timestamp
	MembersCanEditComments         pgtype.Bool
	MembersCanRaiseMotions         bool
	MembersCanVote                 bool
	MembersCanStartDiscussions     bool
	MembersCanCreateSubgroups      bool
	CreatorID                      pgtype.Int4
	IsReferral                     bool
	CohortID                       pgtype.Int4
	DefaultGroupCoverID            pgtype.Int4
	SubscriptionID                 pgtype.Int4
	InvitationsCount               int32
	AdminMembershipsCount          int32
	PublicDiscussionsCount         int32
	Country                        pgtype.Text
	Region                         pgtype.Text
	City                           pgtype.Text
	ClosedMotionsCount             int32
	EnableExperiments              pgtype.Bool
	AnalyticsEnabled               bool
	ProposalOutcomesCount          int32
	Experiences                    []byte
	PendingMembershipsCount        int32
	Features                       []byte
	RecentActivityCount            int32
	ClosedPollsCount               int32
	PollsCount                     int32
	SubgroupsCount                 int32
	OpenDiscussionsCount           int32
	ClosedDiscussionsCount         int32
	Token                          pgtype.Text
	AdminTags                      pgtype.Text
	MembersCanAnnounce             bool
	DescriptionFormat              string
	Attachments                    []byte
	Info                           []byte
	NewThreadsMaxDepth             int32
	NewThreadsNewestFirst          bool
	AdminsCanEditUserContent       bool
	ListedInExplore                bool
	SecretToken                    pgtype.Text
	ContentLocale                  pgtype.Text
	MembersCanAddGuests            bool
	MembersCanDeleteComments       bool
	LinkPreviews                   []byte
	TemplateDiscussionsCount       int32
}

type GroupIdentity struct {
	ID           int32
	GroupID      int32
	IdentityID   int32
	CustomFields []byte
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type GroupSurvey struct {
	ID             int64
	GroupID        int32
	Category       pgtype.Text
	Location       pgtype.Text
	Size           pgtype.Text
	Declaration    pgtype.Text
	Purpose        pgtype.Text
	Usage          pgtype.Text
	Referrer       pgtype.Text
	Role           pgtype.Text
	Website        pgtype.Text
	Misc           pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DesiredFeature pgtype.Text
	Segment        pgtype.Text
}

type LoginToken struct {
	ID             int32
	UserID         pgtype.Int4
	Token          pgtype.Text
	Used           bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Redirect       pgtype.Text
	Code           int32
	IsReactivation bool
}

type Membership struct {
	ID                   int32
	GroupID              pgtype.Int4
	UserID               pgtype.Int4
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	InviterID            pgtype.Int4
	ArchivedAt           pgtype.Timestamp
	InboxPosition        pgtype.Int4
	Admin                bool
	Volume               pgtype.Int4
	Experiences          []byte
	InvitationID         pgtype.Int4
	Token                pgtype.Text
	AcceptedAt           pgtype.Timestamp
	Title                pgtype.Text
	SamlSessionExpiresAt pgtype.Timestamp
}

type MembershipRequest struct {
	ID           int32
	Name         pgtype.Text
	Email        pgtype.Text
	Introduction pgtype.Text
	GroupID      pgtype.Int4
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	RequestorID  pgtype.Int4
	ResponderID  pgtype.Int4
	Response     pgtype.Text
	RespondedAt  pgtype.Timestamp
}

type Notification struct {
	ID                int32
	UserID            pgtype.Int4
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	EventID           pgtype.Int4
	Viewed            bool
	TranslationValues []byte
	Url               pgtype.Text
	ActorID           pgtype.Int4
}

type OauthAccessGrant struct {
	ID              int32
	ResourceOwnerID int32
	ApplicationID   int32
	Token           string
	ExpiresIn       int32
	RedirectUri     string
	CreatedAt       pgtype.Timestamp
	RevokedAt       pgtype.Timestamp
	Scopes          pgtype.Text
}

type OauthAccessToken struct {
	ID              int32
	ResourceOwnerID pgtype.Int4
	ApplicationID   pgtype.Int4
	Token           string
	RefreshToken    pgtype.Text
	ExpiresIn       pgtype.Int4
	RevokedAt       pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	Scopes          pgtype.Text
}

type OauthApplication struct {
	ID              int32
	Name            string
	Uid             string
	Secret          string
	RedirectUri     string
	Scopes          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	OwnerID         pgtype.Int4
	OwnerType       pgtype.Text
	LogoFileName    pgtype.Text
	LogoContentType pgtype.Text
	LogoFileSize    pgtype.Int4
	LogoUpdatedAt   pgtype.Timestamp
}

type OmniauthIdentity struct {
	ID           int32
	UserID       pgtype.Int4
	Email        pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IdentityType pgtype.Text
	Uid          pgtype.Text
	Name         pgtype.Text
	AccessToken  pgtype.Text
	Logo         pgtype.Text
	CustomFields []byte
}

type Outcome struct {
	ID              int32
	PollID          pgtype.Int4
	Statement       string
	AuthorID        int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Latest          bool
	PollOptionID    pgtype.Int4
	CustomFields    []byte
	StatementFormat string
	Attachments     []byte
	SecretToken     pgtype.Text
	VersionsCount   int32
	ReviewOn        pgtype.Date
	ContentLocale   pgtype.Text
	LinkPreviews    []byte
}

type PartitionSequence struct {
	Key     string
	ID      int32
	Counter pgtype.Int4
}

type Poll struct {
	ID                     int32
	AuthorID               int32
	Title                  string
	Details                pgtype.Text
	ClosingAt              pgtype.Timestamp
	ClosedAt               pgtype.Timestamp
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	DiscussionID           pgtype.Int4
	Key                    string
	PollType               string
	StanceData             []byte
	VotersCount            int32
	MultipleChoice         bool
	CustomFields           []byte
	StanceCounts           []byte
	GroupID                pgtype.Int4
	MatrixCounts           []byte
	NotifyOnParticipate    bool
	Example                bool
	UndecidedVotersCount   int32
	VoterCanAddOptions     bool
	GuestGroupID           pgtype.Int4
	Anonymous              bool
	VersionsCount          pgtype.Int4
	DetailsFormat          string
	Attachments            []byte
	AnyoneCanParticipate   bool
	HideResultsUntilClosed bool
	StancesInDiscussion    bool
	DiscardedAt            pgtype.Timestamp
	DiscardedBy            pgtype.Int4
	SecretToken            pgtype.Text
	SpecifiedVotersOnly    bool
	NotifyOnClosingSoon    int32
	ContentLocale          pgtype.Text
	LinkPreviews           []byte
	ShuffleOptions         bool
	AllowLongReason        bool
	HideResults            int32
	ChartType              pgtype.Text
	MinScore               pgtype.Int4
	MaxScore               pgtype.Int4
	MinimumStanceChoices   pgtype.Int4
	MaximumStanceChoices   pgtype.Int4
	DotsPerPerson          pgtype.Int4
	ProcessName            pgtype.Text
	Template               bool
	SourceTemplateID       pgtype.Int4
	ReasonPrompt           pgtype.Text
	PollOptionNameFormat   pgtype.Text
	StanceReasonRequired   int32
	LimitReasonLength      bool
	DefaultDurationInDays  pgtype.Int4
	AgreeTarget            pgtype.Int4
	ProcessSubtitle        pgtype.Text
}

type PollOption struct {
	ID          int32
	Name        string
	PollID      pgtype.Int4
	Priority    int32
	ScoreCounts []byte
	VoterScores []byte
	TotalScore  int32
	VoterCount  int32
	Icon        pgtype.Text
	Meaning     pgtype.Text
	Prompt      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PollUnsubscription struct {
	ID        int32
	PollID    int32
	UserID    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Reaction struct {
	ID            int32
	ReactableID   pgtype.Int4
	UserID        pgtype.Int4
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Reaction      string
	ReactableType string
}

type ReceivedEmail struct {
	ID        int64
	GroupID   pgtype.Int4
	Headers   interface{}
	BodyText  pgtype.Text
	BodyHtml  pgtype.Text
	SpfValid  bool
	DkimValid bool
	Released  bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stance struct {
	ID            int32
	PollID        int32
	ParticipantID pgtype.Int4
	Reason        pgtype.Text
	Latest        bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	VersionsCount pgtype.Int4
	ReasonFormat  string
	Attachments   []byte
	CastAt        pgtype.Timestamp
	Token         pgtype.Text
	RevokedAt     pgtype.Timestamp
	Admin         bool
	InviterID     pgtype.Int4
	Volume        int32
	AcceptedAt    pgtype.Timestamp
	ContentLocale pgtype.Text
	SecretToken   pgtype.Text
	LinkPreviews  []byte
	OptionScores  []byte
	RevokerID     pgtype.Int4
}

type StanceChoice struct {
	ID           int32
	StanceID     pgtype.Int4
	PollOptionID pgtype.Int4
	Score        int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Subscription struct {
	ID                     int32
	ExpiresAt              pgtype.Timestamp
	ChargifySubscriptionID pgtype.Int4
	Plan                   pgtype.Text
	PaymentMethod          string
	OwnerID                pgtype.Int4
	MaxThreads             pgtype.Int4
	MaxMembers             pgtype.Int4
	MaxOrgs                pgtype.Int4
	State                  string
	MembersCount           pgtype.Int4
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	Info                   []byte
	CanceledAt             pgtype.Timestamp
	ActivatedAt            pgtype.Timestamp
	RenewsAt               pgtype.Timestamp
	RenewedAt              pgtype.Timestamp
}

type Tag struct {
	ID            int32
	GroupID       pgtype.Int4
	Name          interface{}
	Color         pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	TaggingsCount pgtype.Int4
	Priority      int32
}

type Tagging struct {
	ID           int32
	TagID        int32
	TaggableID   int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	TaggableType string
}

type Task struct {
	ID          int64
	RecordType  pgtype.Text
	RecordID    pgtype.Int8
	AuthorID    int64
	Uid         int32
	Name        string
	Done        bool
	DoneAt      pgtype.Timestamp
	DueOn       pgtype.Date
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DiscardedAt pgtype.Timestamp
	DoerID      pgtype.Int4
	Remind      pgtype.Int4
	RemindAt    pgtype.Timestamp
}

type TasksUser struct {
	ID        int64
	TaskID    pgtype.Int8
	UserID    pgtype.Int8
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Translation struct {
	ID               int32
	TranslatableID   pgtype.Int4
	TranslatableType pgtype.Text
	Fields           interface{}
	Language         pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type User struct {
	ID                           int32
	Email                        interface{}
	EncryptedPassword            pgtype.Text
	ResetPasswordToken           pgtype.Text
	ResetPasswordSentAt          pgtype.Timestamp
	RememberCreatedAt            pgtype.Timestamp
	SignInCount                  pgtype.Int4
	CurrentSignInAt              pgtype.Timestamp
	LastSignInAt                 pgtype.Timestamp
	CreatedAt                    pgtype.Timestamp
	UpdatedAt                    pgtype.Timestamp
	Name                         pgtype.Text
	DeactivatedAt                pgtype.Timestamp
	IsAdmin                      pgtype.Bool
	AvatarKind                   string
	UploadedAvatarFileName       pgtype.Text
	UploadedAvatarContentType    pgtype.Text
	UploadedAvatarFileSize       pgtype.Int4
	UploadedAvatarUpdatedAt      pgtype.Timestamp
	AvatarInitials               pgtype.Text
	Username                     pgtype.Text
	EmailWhenProposalClosingSoon bool
	AuthenticationToken          pgtype.Text
	UnsubscribeToken             pgtype.Text
	MembershipsCount             int32
	UsesMarkdown                 bool
	SelectedLocale               pgtype.Text
	TimeZone                     pgtype.Text
	Key                          pgtype.Text
	DetectedLocale               pgtype.Text
	EmailCatchUp                 bool
	EmailApiKey                  pgtype.Text
	EmailWhenMentioned           bool
	EmailOnParticipation         bool
	DefaultMembershipVolume      int32
	Country                      pgtype.Text
	Region                       pgtype.Text
	City                         pgtype.Text
	Experiences                  []byte
	FacebookCommunityID          pgtype.Int4
	SlackCommunityID             pgtype.Int4
	RememberToken                pgtype.Text
	ShortBio                     string
	EmailVerified                bool
	Location                     string
	LastSeenAt                   pgtype.Timestamp
	LegalAcceptedAt              pgtype.Timestamp
	EmailNewsletter              bool
	FailedAttempts               int32
	UnlockToken                  pgtype.Text
	LockedAt                     pgtype.Timestamp
	ShortBioFormat               string
	Attachments                  []byte
	CurrentSignInIp              *netip.Addr
	LastSignInIp                 *netip.Addr
	SecretToken                  pgtype.Text
	ContentLocale                pgtype.Text
	Bot                          bool
	LinkPreviews                 []byte
	EmailCatchUpDay              pgtype.Int4
	DateTimePref                 pgtype.Text
}

type UserDeactivationResponse struct {
	ID     int32
	UserID pgtype.Int4
	Body   pgtype.Text
}

type Version struct {
	ID            int32
	ItemType      string
	ItemID        int32
	Event         string
	Whodunnit     pgtype.Int4
	CreatedAt     pgtype.Timestamp
	ObjectChanges []byte
}

type Webhook struct {
	ID               int64
	GroupID          int32
	Name             string
	Url              pgtype.Text
	EventKinds       []byte
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	Format           pgtype.Text
	IncludeBody      pgtype.Bool
	IncludeSubgroups bool
	IsBroken         bool
	Token            pgtype.Text
	AuthorID         pgtype.Int4
	ActorID          pgtype.Int4
	Permissions      []string
}
